### ISSUE TITLE
PasswordSearch with multiple search strings

### ISSUE THREAD

**Issue by GoogleCodeExporter** [joshdrummond/webpasswordsafe#86]
```
Please describe desired steps of proposed new feature/enhancement:

1. We want to have the possibility to search for new passwords with multiple 
search strings. Can we arrive this? The search should match for explenation, 
when the user writes into the search list the two strings "chief" and "root" 
then every passwords should be displayed which contain chief or root or chief 
and root.


What version of the product are you using? On what operating system?

v.1.2.1


```

Original issue reported on code.google.com by `heindl...@googlemail.com` on 27 Jun 2013 at 3:47

**Comment by mateuszskala** [comment]
For me it's not working becouse for all searchTerms You add all finded passwords to passwordSet in PasswordServiceImpl.java
I have fixed this by code:

<pre>
--- <html>PasswordServiceImpl.java (<b>d133399</b>)</html>
+++ <html><b>Current File</b></html>
@@ -253,10 +253,17 @@
         else
         {
             Set<Password> passwordSet = new HashSet<Password>();
+            Boolean firstSearchTerm=true;
             for (String searchTerm : searchTerms)
             {
+                if (firstSearchTerm) {
                 passwordSet.addAll(passwordDAO.findPasswordByFuzzySearch(searchTerm, loggedInUser, activeOnly, tags, tagMatch));
+                firstSearchTerm=false;
             }
+                else{
+                    passwordSet.retainAll(passwordDAO.findPasswordByFuzzySearch(searchTerm, loggedInUser, activeOnly, tags, tagMatch));
+                }
+            }
             passwords.addAll(passwordSet);
         }
         Collections.sort(passwords);
</pre>
